//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _128_128_5a2627baa09bd2c6 {
            get {
                object obj = ResourceManager.GetObject("128_128_5a2627baa09bd2c6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 @Echo Off
        ///cls
        ///osql -E -i xy.dat 的本地化字符串。
        /// </summary>
        internal static string aa {
            get {
                return ResourceManager.GetString("aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*此文件非专业人士请不要修改！*/
        ///if exists (select * from sysobjects where name =&apos;killspid&apos;)
        ///	drop procedure killspid
        ///go
        ///create proc [dbo].[killspid] (@dbname varchar(20))
        ///as
        ///begin
        ///declare @sql nvarchar(500)
        ///declare @spid int
        ///set @sql=&apos;declare getspid cursor for 
        ///select spid from sysprocesses where dbid=db_id(&apos;&apos;&apos;+@dbname+&apos;&apos;&apos;)&apos;
        ///exec (@sql)
        ///open getspid
        ///fetch next from getspid into @spid
        ///while @@fetch_status&lt;&gt;-1
        ///begin
        ///exec(&apos;kill &apos;+@spid)
        ///fetch next from getspid into @spid
        ///end
        ///close getspid
        ///deallocate ge [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string aa1 {
            get {
                return ResourceManager.GetString("aa1", resourceCulture);
            }
        }
    }
}
